name: traccar_client
author: synw <ansterj@gmail.com>
description: Dart client for the Traccar geolocation server. Get real time devices positions from a Traccar server.
homepage: https://github.com/synw/traccar_client
version: 0.1.0

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  web_socket_channel: ^1.1.0
  dio: ^3.0.10
  latlong: ^0.6.1
  pedantic: ^1.9.2
  meta: ^1.2.2
  geopoint: ^0.7.1
  device:
    path: ../device